Elor/urls.py
from django.conf.urls import url,include
from Elor import views

app_name = 'Elor'

urlpatterns = [
    url(r'about/',views.about,name='about'),
    url(r'CV/',views.CV,name='CV'),
    url(r'photography/',views.photography,name='photography'),
    url(r'public_appearence/',views.public_appearence,name='public_appearence'),
    url(r'writing/', views.writing, name='writing'),
]

Home/urls.py
from django.conf.urls import url,include
from Home import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
]

Lynn/urls.py
from django.conf.urls import url,include
from Lynn import views

app_name = 'Lynn'

urlpatterns = [
    url(r'about/',views.about,name='about'),
    url(r'CV/',views.CV,name='CV'),
    url(r'MD/',views.MD,name='MD'),
    url(r'art/',views.art,name='art'),
    url(r'photography/',views.photography,name='photography'),
    url(r'music/',views.music,name='music'),
]

our_site/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Home import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^contact/',views.contact,name='contact'),
    url(r'^travel/',views.travel,name='travel'),
    url(r'^Elor/',include('Elor.urls'),name="Elor"),
    url(r'^Lynn/',include('Lynn.urls'),name="Lynn"),
    url(r'^admin/', admin.site.urls),
]

Elor/models.py
from django.db import models

# Create your models here.

Home/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics')

    def __str__(self):
        return self.user.username

Lynn/models.py
from django.db import models

# Create your models here.

Home/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.forms import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    # portfolio = forms.URLField(required=False)
    # picture = forms.ImageField(required=False)

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio','picture')

Elor/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    return render(request,'Elor/about.html')

def CV(requset):
    return render(requset,'Elor/CV.html')

def photography(request):
    return render(request,'Elor/photography.html')

def public_appearence(requset):
    return render(requset,'Elor/public_appearence.html')

def writing(requset):
    return render(requset,'Elor/writing.html')

Home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'Home/index.html')

def contact(requset):
    return render(requset,'Home/contact.html')

def travel(request):
    return render(request,'Home/travel.html')

Lynn/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    return render(request,'Lynn/about.html')

def CV(requset):
    return render(requset,'Lynn/CV.html')

def MD(requset):
    return render(requset,'Lynn/MD.html')

def art(requset):
    return render(requset,'Lynn/art.html')

def photography(requset):
    return render(requset,'Lynn/photography.html')

def music(requset):
    return render(requset,'Lynn/music.html')

templates/Elor/CV.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Elor: CV</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Elor/about.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Elor: about</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Elor/photography.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Elor: photography</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Elor/public_appearence.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Elor: public</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Elor/writing.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Elor: writing</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Home/contact.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<style>
  #map {
    height: 400px;
    width: 100%;
   }
</style>
<div class="container">
    <div class="jumbotron">
        <h1>Contact us</h1>
        <p></p>
        <h3>Elor:</h3>
        <ul>
            <li>Email: <a href="mailto:elor.arieli@gmail.com">elor.arieli@gmail.com</a></li>
            <li>Facebook: <a href="https://www.facebook.com/elor.arieli">elor.arieli</a></li>
        </ul>
        <p></p>
        <h3>Lynn:</h3>
        <ul>
            <li>Email: <a href="mailto:lynnavital@gmail.com">lynnavital@gmail.com</a></li>
            <li>Facebook: <a href="https://www.facebook.com/lynn.avital.5">lynn.avital.5</a></li>
            <li>Instagram: <a href="https://instagurum.com/u/lynnoosh">@lynnoosh</a></li>
        </ul>
        <p></p>
        <p></p>
        <h3>Where to find us:</h3>
        <p>After working hours ;)</p>
        <div id="map"></div>
        <script>
          function initMap() {
            var uluru = {lat: 32.070283, lng: 34.777434};
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 13,
              center: uluru
            });
            var marker = new google.maps.Marker({
              position: uluru,
              map: map
            });
          }
        </script>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC3Tv8YFBOzUBQ4tMp_n0qEHG82RFw1Zgg&callback=initMap">
        </script>
        </div>
</div>
{% endblock %}
</html>

templates/Home/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<link rel="stylesheet" href="{% static "CSS_files/index_style.css" %}">
<div class="container">
    <div class="jumbotron">
        <h1 align="center">Welcome to the Arieli-Avital household site</h1>
        <h2>A little about us:</h2>
        <h3>Elor:</h3>
        <p>some stuff</p>
        <h3>Lynn:</h3>
        <p>some stuff</p>
        <h3>Our Rats:</h3>
        <ol>
            <li style="float: left">Sleeping together:</li>
                <p style="float: left;">
                <img HEIGHT="240" width="320" src="{% static "rats/all/main.jpg" %}" style="float: right;" />
                This is our wonderful group all cuddled up together to enjoy the warmth and comfort during the night
                </p>
            <li style="float: left">Luna:</li>
                <p style="float: left;">
                <img HEIGHT="240" width="320" src="{% static "rats/luna/main.jpg" %}" style="float: right;" />
                Luna is one of our original duo. she is pure white curly fur and is the cutest of them all! she has a very easy going nature! she is also very cuddly and motherly. we love her!
                </p>

            <li style="float: left">Pandi:</li>
                <p style="float: left;">
                <img HEIGHT="240" width="320" src="{% static "rats/pandi/main.jpg" %}" style="float: right;" />
                Pandi is half black and half white, also one of the 2 originals, she is very smart! has a bit of a tilt problem. loves to play and climb up to our shoulders
                </p>

            <li style="float: left">Suzi:</li>
                <p style="float: left;">
                <img HEIGHT="240" width="320" src="{% static "rats/suzi/main.jpg" %}" style="float: right;" />
                Suzi is half white half light brown. she is very active but also a little scared. she loves to play with her sister Nikki.
                </p>

            <li style="float: left">Nikki:</li>
                <p style="float: left;">
                <img HEIGHT="240" width="320" src="{% static "rats/nikki/main.jpg" %}" style="float: right;" />
                Nikki is half white and half black like pandi, she is maybe the most active and smartest of them all, she has learned how to open and close doors.
                </p>

            <li style="float: left">Pikachu:</li>
                <p style="float: left;">
                <img HEIGHT="240" width="320" src="{% static "rats/pikachu/main.jpg" %}" style="float: right;" />
                Pikachu is a bit like courage the cowardly dog, he wants to go on adventures but everything scares him. he doesn't really like cuddling but my god look at those ears!
                </p>

            <li style="float: left">Munch (R.I.P):</li>
                <p style="float: left;">
                <img HEIGHT="320" width="240" src="{% static "rats/munch/main.jpg" %}" style="float: right;" />
                Munch was pikachu's brother and had a very similiar character. sadly he died due to an illness.
                </p>
        </ol>
    </div>
</div>
{% endblock %}
</html>

templates/Home/travel.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}
<link rel="stylesheet" href="{% static "CSS_files/travel.css" %}">
<div class="container">
    <div class="jumbotron">
        <h1>One of our favorite things to do is travel</h1>
        <h2>Here you can check out a selection of our trips</h2>
        <p></p>
        <h3>Romania 2017:</h3>
        <div class="slideshow-container">
          <div class="mySlides">
            <div class="numbertext">1 / 3</div>
            <img src="{% static "travel/romania/1.jpg" %}" style="width:100%">
            <div class="text">Caption Text</div>
          </div>

          <div class="mySlides">
            <div class="numbertext">2 / 3</div>
            <img src="{% static "travel/romania/2.jpg" %}" style="width:100%">
            <div class="text">Caption Two</div>
          </div>

          <div class="mySlides">
            <div class="numbertext">3 / 3</div>
            <img src="{% static "travel/romania/3.jpg" %}" style="width:100%">
            <div class="text">Caption Three</div>
          </div>

          <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
          <a class="next" onclick="plusSlides(1)">&#10095;</a>
        </div>
        <br>

        <div style="text-align:center">
          <span class="dot" onclick="currentSlide(1)"></span>
          <span class="dot" onclick="currentSlide(2)"></span>
          <span class="dot" onclick="currentSlide(3)"></span>
        </div>
        <p></p>
        <h3>Peru 2015:</h3>
        <p></p>
        <h3>Equador 2015:</h3>
        <p></p>
        <h3>Galapagos Islands 2015:</h3>
        <p></p>
        <h3>Prague 2015:</h3>
        <p></p>
    </div>
</div>
<script src="{% static "JS/travel.js" %}"></script>
{% endblock %}
</html>

templates/Lynn/CV.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Lynn: CV</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Lynn/MD.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Lynn: MD</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Lynn/about.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Lynn: about</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Lynn/art.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Lynn: art</h1>
    </div>
</div>
{% endblock %}
</html>

templates/Lynn/music.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <div class="page-header">
        <h1>Lynn: music</h1>
        </div>
        <h3>Symphony by Clean bandit</h3>
        <p>this is one of my favorite songs.</p>
        <p><a href="https://www.youtube.com/watch?v=aatr_2MstrI">youtube link</a></p>
        <P>enjoy:
        <audio controls>
          <source src="{% static "Lynn/music/Symphony.mp3" %}" type="audio/mpeg">
          Your browser does not support the audio element.
        </audio>
        </P>
    </div>
</div>
{% endblock %}
</html>

templates/Lynn/photography.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Lynn: photography</h1>
    </div>
</div>
{% endblock %}
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Arieli-Avital household</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "CSS_files/base.css" %}">
    <script src="http://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">

      <!-- Inside of a Container -->
    <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- This is the actual code that create the "hamburger icon" -->
      <!-- The data-target grabs ids to put into the icon -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

          <!--  Code for the hamburger icon-->
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      </div>

      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="{% url 'Elor:about' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">Elor<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'Elor:about' %}">About</a></li>
              <li><a href="{% url 'Elor:CV' %}">Curriculum Vitae</a></li>
              <li><a href="{% url 'Elor:public_appearence' %}">Public Appearences</a></li>
              <li><a href="{% url 'Elor:writing' %}">Writing</a></li>
              <li><a href="{% url 'Elor:photography' %}">Photography</a></li>

            </ul>
          </li>

            <li class="dropdown">
            <a href="{% url 'Lynn:about' %}" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">Lynn <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'Lynn:about' %}">About</a></li>
              <li><a href="{% url 'Lynn:CV' %}">Curriculum Vitae</a></li>
              <li><a href="{% url 'Lynn:art' %}">Art</a></li>
              <li><a href="{% url 'Lynn:photography' %}">Photography</a></li>
              <li><a href="{% url 'Lynn:MD' %}">M.D.</a></li>
              <li><a href="{% url 'Lynn:music' %}">Music</a></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" aria-haspopup="true" aria-expanded="false">Rats <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="http://www.google.com">Go to Google</a></li>
              <li><a href="#">Something else here</a></li>

              <!-- Use this to separate a new link -->

              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <li><a href="{% url 'travel' %}">Travel</a></li>
          <li><a href="{% url 'contact' %}">Contact Us</a></li>
        </ul>
      </div>
    </div>
    </nav>
    {% block body_block %}
    {% endblock %}
</body>
</html>